React redux finger exercises
wolox-training/finger-exercises pull request #9
Opened 2018-10-19 23:28 UTC by henryzarza

# Summary
Finger exercise of `Redux`

# Trello Card
https://trello.com/c/PEec6RtL/10-finger-exercise-redux-i

# Screenshots
![redux](https://user-images.githubusercontent.com/28515670/47247963-90260500-d3cc-11e8-9f70-7982f6d62e1f.gif)

2018-10-22 14:07 UTC, marianozicavo commented
The base of this PR should be `react` instead of `master`

2018-10-23 19:19 UTC, mvbattan reviewed
Hey, great job !! 👏 Looks really nice !!
I'm leaving a few comments !

2018-10-23 19:19 UTC, mvbattan commented on react/redux/01 - actions/actions.js
> +  ADD_READ_BOOK: 'ADD_READ_BOOK'
I'd add a namespace to these action names:
```
SET_FAVORITE_BOOK: '@@BOOK/SET_FAVORITE_BOOK'
```

2018-10-23 19:19 UTC, mvbattan commented on react/redux/01 - actions/store.js
> +createStore(reducer);
`export default` ?

2018-10-23 19:19 UTC, mvbattan commented on react/redux/01 - actions/reducer.js
> +  readBooks: ['otro libro']
I'd write this in english 😊

2018-10-23 19:19 UTC, mvbattan commented on react/redux/01 - actions/test.js
> +    expect(store.getState().readBooks).toEqual(['otro libro', 'The Lord of the Rings']);
I'd write this in english 😊

2018-10-23 19:19 UTC, mvbattan commented on react/redux/redux/src/app/screens/App/components/Book/index.js
> +            <div />
What's the purpose of this `div` ?

2018-10-23 19:19 UTC, mvbattan commented on react/redux/redux/src/app/screens/App/components/Book/index.js
> +            <div />
What's the purpose of these `divs` ?

2018-10-23 19:19 UTC, mvbattan commented on react/redux/redux/src/app/screens/App/components/Book/index.js
> +            <div>
Is this doable using a `Fragment` ? Do we need these `divs` ?

2018-10-23 19:19 UTC, mvbattan commented on react/redux/redux/src/app/screens/App/components/Book/styles.scss
> +      }
👏

2018-10-23 19:19 UTC, mvbattan commented on react/redux/redux/src/app/screens/App/index.js
> +    });
It will be great to let the trainees translate this to `mapStateToProps / mapDispatchToProps` 😊

2018-10-23 19:19 UTC, mvbattan commented on react/redux/redux/src/redux/book/actions.js
> +  SEARCH_ITEM: 'SEARCH_ITEM'
I'd add `namespaces` here

2018-10-25 23:13 UTC, henryzarza commented on react/redux/01 - actions/store.js
> +createStore(reducer);
This isn't mine

2018-10-25 23:14 UTC, henryzarza commented on react/redux/01 - actions/reducer.js
> +  readBooks: ['otro libro']
The same here

2018-10-25 23:14 UTC, henryzarza commented on react/redux/01 - actions/test.js
> +    expect(store.getState().readBooks).toEqual(['otro libro', 'The Lord of the Rings']);
And here

2018-10-25 23:15 UTC, henryzarza commented on react/redux/redux/src/app/screens/App/components/Book/index.js
> +            <div />
This is necessary for the effect the book

2018-10-25 23:15 UTC, henryzarza commented on react/redux/redux/src/app/screens/App/components/Book/index.js
> +            <div />
The same answer here

2018-10-25 23:18 UTC, henryzarza commented on react/redux/redux/src/app/screens/App/components/Book/index.js
> +            <div>
The same answer here

2018-10-25 23:21 UTC, henryzarza commented on react/redux/redux/src/app/screens/App/index.js
> +    });
I think the same 👍

2018-10-29 18:04 UTC, mvbattan approved these changes
Remember to remove `.DS_Store` files !

2018-10-29 18:04 UTC, mvbattan commented on react/redux/01 - actions and reducers/books/actions.js
> +related to @@BOOKS for easier debugging.
😍

2018-10-30 14:13 UTC, marianozicavo requested changes

2018-10-30 14:13 UTC, marianozicavo commented on react/redux/02 - react-redux/src/app/screens/App/components/Book/index.js
> +    name: string,
You´re missing `id`

2018-10-30 14:13 UTC, marianozicavo commented on react/redux/02 - react-redux/src/app/screens/App/index.js
> +    const isSelected = this.state.bookSelected.findIndex(el => el.id === item.id) === -1;
Use `this.state.bookSelected.some(el => el.id === item.id)`

2018-10-30 14:13 UTC, marianozicavo commented on react/redux/02 - react-redux/src/app/screens/App/index.js
> +    const isSelected = this.state.bookSelected.findIndex(el => el.id === item.id) === -1;
Is the variable name right? You´re using `isSelected` to mean the ones that aren´t on the cart.

2018-10-30 14:13 UTC, marianozicavo commented on react/redux/02 - react-redux/src/app/screens/App/index.js
> +    return <Book key={item.id} data={item} isSelected={isSelected} handleClick={this.addToCart} />;
I'd rename `handleClick` to `onClick`

2018-10-30 14:13 UTC, marianozicavo commented on react/redux/02 - react-redux/src/app/screens/App/components/Book/index.js
> +    handleClick({ id, name, quantity: 1 });
I don't like that there are two `handleClick`s here.

2018-10-30 14:13 UTC, marianozicavo commented on react/redux/02 - react-redux/src/redux/book/reducer.js
> +          quantity: el.id === action.payload ? (el.quantity += 1) : el.quantity
⚠️Watch out! You're mutating the state when you do `el.quantity += 1`

2018-10-30 14:13 UTC, marianozicavo commented on react/redux/02 - react-redux/src/app/screens/App/components/ShoppingCart/index.js
> +        <div className={`${styles.container} ${this.state.open ? styles.open : ''}`}>
I don't like the idea of the shopping cart and the button to open the shopping cart being the same component.
I think it would be good exercise to give the trainees: to move the open/closed state to the store and separate this components.
What do you think @henryzarza  @mvbattan ?

2018-10-30 23:13 UTC, henryzarza commented on react/redux/02 - react-redux/src/app/screens/App/components/ShoppingCart/index.js
> +        <div className={`${styles.container} ${this.state.open ? styles.open : ''}`}>
I'm agree with to move the open/closed state to the store. But i don't understand the reason of the first recommendation @marianozicavo

2018-10-31 16:48 UTC, mvbattan commented on react/redux/02 - react-redux/src/app/screens/App/components/ShoppingCart/index.js
> +        <div className={`${styles.container} ${this.state.open ? styles.open : ''}`}>
@marianozicavo @henryzarza Agree with open/closed state comment 😄 
I think that is it fine for the scope of this finger exercise to have a low-complexity components tree. I'd let this as is.
Maybe I'd extract this one to a subcomponent, but I think that this component is understandable and render lines are acceptable (~10 lines).

2018-10-31 16:49 UTC, mvbattan commented on react/redux/02 - react-redux/src/redux/book/reducer.js
> +          quantity: el.id === action.payload ? (el.quantity += 1) : el.quantity
I think this part will be deleted 🤔

2018-10-31 18:09 UTC, merged

2018-10-31 18:10 UTC, mvbattan commented
Merged due to W-University implementation